name: Build and Deploy website

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: installing node 13
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: install dependencies
      run: npm i

    - name: Build website files
      env:
        NODE_ENV: production
      run: npm run build


    - name: Commit new files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f docs/*
        git commit -am "Automated website commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
